# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02122cdd3d899b513b7eaf1d0fbf742f8bb5e73cab547dd119394643c8131cfb39f48aaf09f019516756bcefac26be286aa7195a6665239dc92e719cb80a067d

test:
  secret_key_base: a31982da689532f6f0d76959ea20d16a43c67a0235b4a37e9789125afeb2547ba8b5adb60dab5ac1091f14eb116b8d6f97992acce9d4920c024049cee8d9fd34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
